definitions:
  domain.Payment:
    properties:
      amount:
        type: number
      id:
        type: string
      method:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /payments:
    get:
      consumes:
      - application/json
      description: Get All Payments
      operationId: get-all-payments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Payment'
            type: array
    post:
      consumes:
      - application/json
      description: Create a Payment
      operationId: create-payment
      parameters:
      - description: Create Payment
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/domain.Payment'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Payment'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
  /payments/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a Payment
      operationId: delete-payment
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Payment deleted
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
    get:
      consumes:
      - application/json
      description: Get Payment by ID
      operationId: get-payment-by-id
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Payment'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
    put:
      consumes:
      - application/json
      description: Update a Payment
      operationId: update-payment
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Payment
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/domain.Payment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Payment'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
swagger: "2.0"
