name: Deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1.0.0 # ou a versão mais recente disponível
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          SONAR_HOST_URL: https://sonarcloud.io  # Usado se você estiver no SonarCloud

  build:
    runs-on: ubuntu-22.04
    needs: sonarqube # Isso garante que o deploy no Heroku só acontece após o SonarQube ser executado com sucesso
    steps:
      - uses: actions/checkout@v2

      # Adicionar as variáveis do GitHub Actions no Heroku
      - name: Configurar variáveis no Heroku
        run: |
          heroku config:set DB_PASSWORD=${{ secrets.DB_PASSWORD }} --app payments-tec
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "payments-tec"
          heroku_email: "kaique.motta@hotmail.com"
