name: Deploy

on:
  push:
    branches:
      - master  # A branch principal onde o deploy PRE será feito
      - main    # Se você usar `main`, adicione ela também

  release:
    types: [created]  # Ação disparada quando um release é criado

jobs:
  # Job para Build
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Project
        run: |
          echo "Construindo o projeto..."

  # Job para Testes com Cobertura
  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21  # Ajuste para a versão que você usa

      - name: Run Tests with Coverage
        run: |
          go test -v ./... -coverprofile=coverage.out

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.out

  # Job para Análise no SonarQube
  sonarqube:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v4.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          SONAR_HOST_URL: https://sonarcloud.io
          args: >
            -Dsonar.projectKey=kaiquemotta_payments
            -Dsonar.organization=kaiquemotta
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.go.coverage.reportPaths=coverage.out

  # Job para Deploy em Pré-Produção
  deploy_pre:
    runs-on: ubuntu-22.04
    needs: sonarqube
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Configurar variáveis no Heroku
        run: |
          heroku config:set DB_PASSWORD=${{ secrets.DB_PASSWORD }} --app payments-tec
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "payments-tec"
          heroku_email: "kaique.motta@hotmail.com"

  # Job para Deploy em Produção
  deploy_prod:
    runs-on: ubuntu-22.04
    needs: sonarqube
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/checkout@v2

      - name: Configurar variáveis no Heroku
        run: |
          heroku config:set DB_PASSWORD=${{ secrets.DB_PASSWORD }} --app payments-tec-prod
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "payments-tec-prod"
          heroku_email: "kaique.motta@hotmail.com"
