name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.7.0.2747/sonar-scanner-cli-4.7.0.2747-linux.zip
          sudo unzip sonar-scanner.zip -d /opt
          sudo ln -s /opt/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner

      - name: Run SonarQube Analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-go-project \
            -Dsonar.organization=my-organization \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # Configurar variáveis no Heroku
      - name: Configurar variáveis no Heroku
        run: |
          heroku config:set DB_PASSWORD=${{ secrets.DB_PASSWORD }} --app payments-tec
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      # Deploy no Heroku
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "payments-tec"
          heroku_email: "kaique.motta@hotmail.com"
