name: Deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  # Job para Build
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0

      - name: Build Project
        run: |
          # Comandos para build do seu projeto
          echo "Construindo o projeto..."

  # Job para Testes
  test:
    runs-on: ubuntu-22.04
    needs: build # Esse job vai rodar somente após o build ser completado
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Tests
        run: |
          # Comandos para rodar os testes
          echo "Executando os testes..."

  # Job para Análise no SonarQube
  sonarqube:
    runs-on: ubuntu-latest
    needs: test # Esse job vai rodar após os testes
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v4.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          SONAR_HOST_URL: https://sonarcloud.io

  # Job para Deploy em Pré-Produção
  deploy_pre:
    runs-on: ubuntu-22.04
    needs: sonarqube # Esse job vai rodar somente após a análise no SonarQube
    steps:
      - uses: actions/checkout@v2

      - name: Configurar variáveis no Heroku
        run: |
          heroku config:set DB_PASSWORD=${{ secrets.DB_PASSWORD }} --app payments-tec-pre
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "payments-tec-pre"
          heroku_email: "kaique.motta@hotmail.com"

  # Job para Deploy em Produção (será ativado quando você precisar)
  deploy_prod:
    runs-on: ubuntu-22.04
    needs: sonarqube # Esse job será o próximo a rodar, após a análise do SonarQube
    if: github.ref == 'refs/heads/master' # Só roda em 'master' para produção
    steps:
      - uses: actions/checkout@v2

      - name: Configurar variáveis no Heroku
        run: |
          heroku config:set DB_PASSWORD=${{ secrets.DB_PASSWORD }} --app payments-tec-prod
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "payments-tec-prod"
          heroku_email: "kaique.motta@hotmail.com"
